// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA180I1GKLwGMHmbt0h6R_-BSM8B0mVmSY',
    appId: '1:9291541733:web:58d1cae47f5eab2855f80c',
    messagingSenderId: '9291541733',
    projectId: 'spacenews-core-9158b',
    authDomain: 'spacenews-core-9158b.firebaseapp.com',
    storageBucket: 'spacenews-core-9158b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2gcieNx1E_irnId7q8prEqUr5pTB3nHU',
    appId: '1:9291541733:android:d1bfb46002eaadc555f80c',
    messagingSenderId: '9291541733',
    projectId: 'spacenews-core-9158b',
    storageBucket: 'spacenews-core-9158b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARYL1QYjHM-nIhZ3T3u7eWNdla13kV_Oo',
    appId: '1:9291541733:ios:4c60a665b871848555f80c',
    messagingSenderId: '9291541733',
    projectId: 'spacenews-core-9158b',
    storageBucket: 'spacenews-core-9158b.firebasestorage.app',
    iosBundleId: 'com.example.spacenewsCore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARYL1QYjHM-nIhZ3T3u7eWNdla13kV_Oo',
    appId: '1:9291541733:ios:4c60a665b871848555f80c',
    messagingSenderId: '9291541733',
    projectId: 'spacenews-core-9158b',
    storageBucket: 'spacenews-core-9158b.firebasestorage.app',
    iosBundleId: 'com.example.spacenewsCore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA180I1GKLwGMHmbt0h6R_-BSM8B0mVmSY',
    appId: '1:9291541733:web:1fa541260778d3ee55f80c',
    messagingSenderId: '9291541733',
    projectId: 'spacenews-core-9158b',
    authDomain: 'spacenews-core-9158b.firebaseapp.com',
    storageBucket: 'spacenews-core-9158b.firebasestorage.app',
  );
}
